version: "3"
services:
  decentralised-scd-registry-frontend:
    container_name: decentralised-scd-registry-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ipfs-data:/ipfsdata
    ports:
      - 4001:4001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
      - 127.0.0.1:5001:5001
volumes:
  ipfs-data: